forge "https://forgeapi.puppetlabs.com"

# Module for access to NSIDC Enterprise storage
mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => 'latest'

# Python support
mod 'puppet-python, '8.0.0'
