forge "https://forgeapi.puppetlabs.com"

# Module for access to NSIDC Enterprise storage
mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => 'latest'

# Module to install Continuum Analytics Miniconda
mod "nsidc/nsidc_miniconda",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-miniconda.git",
  :ref => 'latest'

# Vault client module
mod "nsidc/nsidc_vault_client",
  :git => "git@bitbucket.org:nsidc/puppet-nsidc-vault-client.git",
  :ref => "v1.0.0"

mod "puppetlabs-postgresql", "10.5.0"
